name: C++ CI Workflow with Google Test

on:
  push:
    branches:
      - master  # Trigger on push to the main branch

jobs:
  build_and_test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Check out the code in the repository

      - name: Set up C++ environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake libgtest-dev g++  # Install build tools, GTest, and C++ compiler

      - name: Compile and run tests
        run: |
          g++ -std=c++11 tests/test.cpp -o test_exec
          ./test_exec
