name: C++ CI Workflow with Google Test

on:
  push:
    branches:
      - master  # Trigger on push to the main branch

jobs:
  build_and_test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Check out the code in the repository

      - name: Set up C++ environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake libgtest-dev g++  # Install build tools, GTest, and C++ compiler

      - name: Install Google Test
        run: |
          # Google Test is typically not pre-installed, so we need to build it from source
          cd /usr/src/gtest
          sudo cmake CMakeLists.txt
          sudo make
          sudo cp libg* /usr/lib

      - name: Build the C++ code and tests
        run: |
          # Create a build directory and navigate into it
          mkdir -p build
          cd build

          # Compile the actual code (Vaja1.cpp) and link it to Google Test library
          g++ -std=c++11 -isystem /usr/include/gtest -L /usr/lib -lgtest -lgtest_main -pthread ../Vaja1.cpp -o Vaja1_test

      - name: Run the tests
        run: |
          # Run the compiled code (Vaja1_test) with the tests
          ./build/Vaja1_test
