jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake libgtest-dev g++

      - name: Compile and run tests with error output
        run: |
          g++ -std=c++11 tests/test.cpp -o test_exec 2> napaka.txt || true
          ./test_exec || true

      - name: Upload error file
        uses: actions/upload-artifact@v3.1.2
        with:
          name: napaka
          path: napaka.txt

  check_error:
    needs: build_and_test
    runs-on: ubuntu-latest

    steps:
      - name: Download napaka.txt
        uses: actions/download-artifact@v3.0.2
        with:
          name: napaka

      - name: Check for errors
        run: |
          if [ -s napaka.txt ]; then
            echo "Errors found in napaka.txt:"
            cat napaka.txt
            exit 1
          else
            echo "No errors, all good."
          fi
